apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: blue-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Blue Version</title>
        <style>
            body { 
                font-family: Arial; 
                text-align: center; 
                margin: 50px;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                min-height: 80vh;
                display: flex;
                flex-direction: column;
                justify-content: center;
            }
            .version { font-size: 3em; margin: 20px; }
            .info { font-size: 1.2em; }
        </style>
    </head>
    <body>
        <div class="version">🔵 BLUE VERSION</div>
        <div class="info">Version 1.0 - Original Application</div>
        <div class="info">Hostname: <span id="hostname"></span></div>
        <div class="info">Time: <span id="time"></span></div>
        
        <script>
            document.getElementById('hostname').textContent = window.location.hostname;
            setInterval(() => {
                document.getElementById('time').textContent = new Date().toLocaleTimeString();
            }, 1000);
        </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: myapp
    version: blue
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app
spec:
  to:
    kind: Service
    name: app
  port:
    targetPort: 80
