apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: green-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: green-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Green Version</title>
        <style>
            body { 
                font-family: Arial; 
                text-align: center; 
                margin: 50px;
                background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
                color: white;
                min-height: 80vh;
                display: flex;
                flex-direction: column;
                justify-content: center;
            }
            .version { font-size: 3em; margin: 20px; }
            .info { font-size: 1.2em; }
            .new-feature { 
                background: rgba(255,255,255,0.2); 
                padding: 20px; 
                margin: 20px; 
                border-radius: 10px; 
            }
        </style>
    </head>
    <body>
        <div class="version">🟢 GREEN VERSION</div>
        <div class="info">Version 2.0 - Updated Application</div>
        <div class="new-feature">
            ✨ NEW FEATURES ✨<br>
            • Improved Performance<br>
            • Better UI Design<br>
            • Enhanced Security
        </div>
        <div class="info">Hostname: <span id="hostname"></span></div>
        <div class="info">Time: <span id="time"></span></div>
        
        <script>
            document.getElementById('hostname').textContent = window.location.hostname;
            setInterval(() => {
                document.getElementById('time').textContent = new Date().toLocaleTimeString();
            }, 1000);
        </script>
    </body>
    </html>
