apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>OpenShift Todo App</title>
        <style>
            body { font-family: Arial; margin: 40px; }
            .todo { padding: 10px; border: 1px solid #ddd; margin: 5px 0; }
            input, button { padding: 8px; margin: 5px; }
        </style>
    </head>
    <body>
        <h1>🚀 OpenShift Todo App</h1>
        <input type="text" id="todoInput" placeholder="Enter todo...">
        <button onclick="addTodo()">Add Todo</button>
        <div id="todos"></div>
        
        <script>
            async function loadTodos() {
                const response = await fetch('/api/todos');
                const todos = await response.json();
                document.getElementById('todos').innerHTML = todos.map(todo => 
                    `<div class="todo">${todo.text}</div>`
                ).join('');
            }
            
            async function addTodo() {
                const text = document.getElementById('todoInput').value;
                if (!text) return;
                
                await fetch('/api/todos', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ text })
                });
                
                document.getElementById('todoInput').value = '';
                loadTodos();
            }
            
            loadTodos();
        </script>
    </body>
    </html>
  nginx.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /api/ {
            proxy_pass http://todo-api:3000;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: html
        configMap:
          name: frontend-html
          items:
          - key: index.html
            path: index.html
      - name: config
        configMap:
          name: frontend-html
          items:
          - key: nginx.conf
            path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  selector:
    app: todo-frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
spec:
  to:
    kind: Service
    name: todo-frontend
  port:
    targetPort: 80
