apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
spec:
  template:
    spec:
      containers:
      - name: load-test
        image: busybox
        command: ["sh", "-c"]
        args:
        - |
          echo "Starting load test..."
          while true; do
            wget -q -O- http://webapp/
            sleep 0.1
          done
      restartPolicy: Never
