apiVersion: v1
kind: ConfigMap
metadata:
  name: python-app
data:
  app.py: |
    from flask import Flask
    import os
    
    app = Flask(__name__)
    
    @app.route('/')
    def hello():
        return '''
        <html>
        <head><title>Python Hello World</title></head>
        <body style="font-family: Arial; text-align: center; margin: 50px;">
            <h1>🐍 Python Hello World on OpenShift!</h1>
            <p>This Flask app is running on OpenShift</p>
            <p>Pod: ''' + os.environ.get('HOSTNAME', 'unknown') + '''</p>
        </body>
        </html>
        '''
    
    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=8080)
  requirements.txt: |
    Flask==2.3.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello
  labels:
    app: python-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-hello
  template:
    metadata:
      labels:
        app: python-hello
    spec:
      containers:
      - name: python-hello
        image: registry.redhat.io/ubi8/python-39
        ports:
        - containerPort: 8080
        command: ["/bin/bash"]
        args: ["-c", "pip install -r /app/requirements.txt && python /app/app.py"]
        volumeMounts:
        - name: app-code
          mountPath: /app
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
      volumes:
      - name: app-code
        configMap:
          name: python-app
---
apiVersion: v1
kind: Service
metadata:
  name: python-hello
spec:
  selector:
    app: python-hello
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: python-hello
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: python-hello
